- src/main/java/io/beanmapper/dynclass/ClassGenerator.java
- src/main/java/io/beanmapper/dynclass/ClassStore.java
- src/test/java/io/beanmapper/dynclass/AbstractConcurrentTest.java
- src/test/java/io/beanmapper/dynclass/ClassGeneratorTest.java
- src/test/java/io/beanmapper/dynclass/ClassStoreTest.java
by adding some synchronization. 
The shared static fields `CACHE` and `GENERATED_CLASS_PREFIX` were potentially accessed concurrently; for example when two requests at the same time want a downsized result. I've added two unit tests to prove the fix/fault. If you want to see the tests fail, just remove the synchronized blocks out of `ClassStore` and `ClassGenerator`.
> Fix for concurrency issues in ClassStore and ClassGenerator 

- src/main/java/io/beanmapper/annotations/BeanParent.java
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/config/Configuration.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/main/java/io/beanmapper/core/converter/AbstractBeanConverter.java
- src/main/java/io/beanmapper/core/converter/BeanConverter.java
- src/main/java/io/beanmapper/core/converter/BeanMapperAware.java
- src/main/java/io/beanmapper/core/converter/collections/AbstractCollectionConverter.java
- src/main/java/io/beanmapper/core/converter/impl/NumberToNumberConverter.java
- src/main/java/io/beanmapper/core/converter/impl/PrimitiveConverter.java
- src/main/java/io/beanmapper/strategy/AbstractMapStrategy.java
- src/main/java/io/beanmapper/strategy/MapToClassStrategy.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/core/converter/AbstractBeanConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/NestedSourceClassToNestedTargetClassConverter.java
- src/test/java/io/beanmapper/core/converter/impl/ObjectToStringConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToBigDecimalConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToBooleanConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToByteConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToDoubleConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToEnumConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToFloatConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToIntegerConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToLongConverterTest.java
- src/test/java/io/beanmapper/core/converter/impl/StringToShortConverterTest.java
- src/test/java/io/beanmapper/testmodel/parent/Player.java
- src/test/java/io/beanmapper/testmodel/parent/PlayerForm.java
- src/test/java/io/beanmapper/testmodel/parent/Skill.java
- src/test/java/io/beanmapper/testmodel/parent/SkillForm.java
#66 Introduces the option to mark a field as a recipient for the pare…nt Object. This is especially handy when the ORM (eg, Hibernate) mappings are based on children needing a reference to the parent. A child can then set its reference to the parent during the mapping phase, which reduces manual mapping and -- as an added bonus -- gives you the option to validate before the controller method is hit.
One caveat I'm not too happy with; the Converter interface is changed to make sure the parent can be passed. The reason for this is that mapping a collection is handled by a converter. This converter then calls the BeanMapper.map method. On this last call it needs to pass the parent. Therefore the converter must know what the parent is. Perhaps there is a better solution for this?
The …
> @BeanParent, to set a target parent on a target child

- .travis.yml
- pom.xml
- src/main/java/io/beanmapper/BeanMapper.java
- src/main/java/io/beanmapper/config/Configuration.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/config/BeanMapperBuilderTest.java
changed converterChoosable primitive boolean to object Boolean to have tri-state and ability to ask parent configs for the ultimate value.
The boolean values changed; Core > false, Override > true, with no lookup. Logic in BeanMapper set the converterChoosable to false if not required. Now we have Core > null, Override > null. Core returns false if null. There is more of a lookup system through the configurations. List mappers in BeanMapper set the Boolean value explicitly to true. Added two tests to verify this.
End result of this change is that converterChoosable can be set when the starter is used.
> converterChoosable is settable on the CoreConfiguration

- pom.xml
- src/main/java/io/beanmapper/annotations/BeanCollection.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/converter/AbstractBeanConverter.java
- src/main/java/io/beanmapper/core/converter/collections/AbstractCollectionConverter.java
- src/main/java/io/beanmapper/core/converter/collections/BeanCollectionInstructions.java
- src/main/java/io/beanmapper/exceptions/BeanCollectionUnassignableTargetCollectionTypeException.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/collections/CollectionSetTargetIncorrectSubtype.java
- src/test/java/io/beanmapper/testmodel/collections/CollectionSetTargetSpecificSubtype.java
It is now possible to define a specific target type of
collection in the @BeanCollection annotation. Previously
in the case of a CONSTRUCT operation a TreeSet was always
created, but this doesn't work for classes that do not
implement Comparable. This way the user has a choice what
target collection type to choose.
> Added targetCollectionType to @BeanCollection annotation

- README.md
- pom.xml
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/PropertyMatchupDirection.java
- src/main/java/io/beanmapper/core/inspector/FieldPropertyAccessor.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/core/inspector/PropertyAccessorTest.java
- src/test/java/io/beanmapper/testmodel/strictconvention/SCSourceAForm.java
- src/test/java/io/beanmapper/testmodel/strictconvention/SCSourceB.java
- src/test/java/io/beanmapper/testmodel/strictconvention/SCSourceCForm.java
- src/test/java/io/beanmapper/testmodel/strictconvention/SCTargetA.java
- src/test/java/io/beanmapper/testmodel/strictconvention/SCTargetBResult.java
- src/test/java/io/beanmapper/testmodel/strictconvention/SCTargetC.java
Issue #78 BeanMapper contained an error in the FieldPropertyAccessor resulting in it always returning true when asked if it was readable. This resulted in more properties being marked as mapping candidates. This then resulted in the strict mapping convention validation failing, because matching properties on the other side were missing.
>  Strict mapping convention also tries to find matches for private fields

- CHANGELOG.md
- src/main/java/io/beanmapper/annotations/BeanCollection.java
- src/main/java/io/beanmapper/annotations/BeanCollectionUsage.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/collections/CollSourceClear.java
- src/test/java/io/beanmapper/testmodel/collections/CollSourceConstruct.java
- src/test/java/io/beanmapper/testmodel/collections/CollSourceReuse.java
- src/test/java/io/beanmapper/testmodel/collections/CollTarget.java
Issue #59 The BeanCollection.beanCollectionUsage has its default changed from REUSE to CLEAR. The dominant option (bar none) is CLEAR, because this resets the target collection's available instance and triggers (for example) a managed list's action (such as deleting orphans for Hibernate). A quick scan of available projects proved this change will not pose a problem at all.
Documentation for BeanCollection has been extended.
> @BeanCollection usage should be CLEAR not REUSE

- CHANGELOG.md
- src/main/java/io/beanmapper/core/inspector/FieldPropertyAccessor.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/enums/UserRole.java
- src/test/java/io/beanmapper/testmodel/enums/UserRoleResult.java
Issue #83 In the resolution of issue #78 the definition of getter fields has been tightened, because previously all private fields were tagged as available as well. One project made use of this loophole by reading the name field of an enumeration class to a String field. With the new fix this is no longer possible, since the name field is private.
This fix makes an exception for the name field of an enum class. It will be considered available for reading.
> The name field from an enum is not mapped to target field

- CHANGELOG.md
- src/main/java/io/beanmapper/annotations/BeanCollection.java
- src/main/java/io/beanmapper/config/AfterClearFlusher.java
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/config/CollectionFlusher.java
- src/main/java/io/beanmapper/config/Configuration.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/collections/AbstractCollectionHandler.java
- src/main/java/io/beanmapper/core/collections/CollectionHandler.java
- src/main/java/io/beanmapper/core/collections/ListCollectionHandler.java
- src/main/java/io/beanmapper/core/collections/MapCollectionHandler.java
- src/main/java/io/beanmapper/core/collections/SetCollectionHandler.java
- src/main/java/io/beanmapper/core/converter/collections/BeanCollectionInstructions.java
- src/main/java/io/beanmapper/core/converter/collections/CollectionConverter.java
- src/main/java/io/beanmapper/strategy/MapCollectionStrategy.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/collections/CollSourceClearFlush.java
Issue #84 states that usage of Hibernate's @OneToMany leads to the known problem of Hibernate first executing its insert, then its delete SQL-statements. When the table uses (as it well should) unique constraints, this leads to a violation. The dirty quickfix is to disable the constraints. The long-term fix is for BeanMapper to force the ORM to flush, effectively reversing the order of delete and insert SQL-statements.
When a clear method on a collection is called, BeanMapper makes sure to run down the list of registered AfterClearFlusher instances. On every instance, the flush method will be called. By default AfterClearFlusher instances are added. BeanMapper has no notion of ORMs; this is left to [beanmapper-spring](https://github.com/42BV/beanmapper-spring) and …
> BeanMapper executes the list of AfterClearFlusher instances

- CHANGELOG.md
- pom.xml
- src/main/java/io/beanmapper/core/BeanField.java
- src/main/java/io/beanmapper/core/BeanMatch.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/BeanPropertyWrapper.java
- src/main/java/io/beanmapper/core/MatchedBeanPairField.java
- src/main/java/io/beanmapper/exceptions/BeanNoSuchPropertyException.java
- src/main/java/io/beanmapper/strategy/AbstractMapStrategy.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/beanproperty/SourceBeanProperty.java
- src/test/java/io/beanmapper/testmodel/beanproperty/SourceNestedBeanProperty.java
- src/test/java/io/beanmapper/testmodel/beanproperty/TargetBeanProperty.java
- src/test/java/io/beanmapper/testmodel/beanproperty/TargetNestedBeanProperty.java
- src/test/java/io/beanmapper/testmodel/beanproperty/TargetNestedBeanPropertyAlpha.java
- src/test/java/io/beanmapper/testmodel/beanproperty/TargetNestedBeanPropertyBeta.java
Issue #60 properties annotated with BeanProperty must match. If they do not, an exception must be thrown. Due to a bug, this did not always occur (only with BeanProperty on the target side). The current mechanism keep tabs on matched properties and does a final verification. If unmatched properties remain that should have been matched, an exception is thrown.
Opened new snapshot version
Added test for #64 to prove it now works
> Unmatched BeanProperty did not throw an exception

- CHANGELOG.md
- src/main/java/io/beanmapper/annotations/BeanCollectionUsage.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/converter/collections/BeanCollectionInstructions.java
- src/main/java/io/beanmapper/core/converter/collections/CollectionConverter.java
- src/main/java/io/beanmapper/core/converter/collections/CollectionElementType.java
- src/main/java/io/beanmapper/dynclass/ClassGenerator.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/collections/CollSourceNoGenerics.java
- src/test/java/io/beanmapper/testmodel/collections/CollSubTargetList.java
- src/test/java/io/beanmapper/testmodel/collections/CollSuperTargetList.java
- src/test/java/io/beanmapper/testmodel/collections/CollTargetEmptyList.java
- src/test/java/io/beanmapper/testmodel/collections/CollTargetListNotAnnotatedUseSetter.java
- src/test/java/io/beanmapper/testmodel/collections/CollTargetNoGenerics.java
Issue #99. Collections in superclasses did not get their generic types read. One of the attributes of getDeclaredField(field) is that it only works on the active class. The fix means that the superclasses will be checked for presence of the field. When found, it will call getDeclaredField on that class to get its generic type. Also, collection mapping instructions are not used when no collection element type can be determined; that is the one crucial element required for mapping collections.
Issue #100. Collections.EmptySet can not have add() called on. BeanCollectionUsage will check the canonical classname of the collection. If it starts with "java.util.Collections.", it will be tagged as reconstructable.
> Collections in super classes & Collections.EmptySet

- src/main/java/io/beanmapper/core/inspector/FieldPropertyAccessor.java
- src/main/java/io/beanmapper/core/inspector/PropertyDescriptorPropertyAccessor.java
- src/test/java/io/beanmapper/core/inspector/PropertyDescriptorPropertyAccessorTest.java
An error sometimes occurred in the BeanMapper when it attempted to
invoke a getter method in the PropertyDescriptorPropertyAccessor.
The short version of the solution:
The setAccessible method should be called very soon prior to calling
the invoke method rather than only once at the creation of the
PropertyDescriptorPropertyAccessor.
For the long version of the solution, let me take you down the
rabbit hole:
The error occurred in the following piece of code, when the 'invoke'
method was called:
@Override
public Object getValue(Object instance) {
if (!isReadable()) {
throw new BeanGetFieldException(instance.getClass(), getName());
}
try {
return descriptor.getReadMethod().invoke(instance);
} catch (IllegalAccessException e) {
throw new BeanGetFieldException(instance.getClass(), getName(), …
> Fixed IllegalAccessExceptions that occurred after JMV garbage collection

- CHANGELOG.md
- src/main/java/io/beanmapper/core/converter/AbstractBeanConverter.java
- src/main/java/io/beanmapper/core/converter/SimpleBeanConverter.java
- src/main/java/io/beanmapper/core/converter/impl/AnyToEnumConverter.java
Literally changed return type Object on doConvert to T. All extensions
will pick up this specification, making it clearer to the using developer 
what return type is expected.
> Specify the return type for AbstractBeanConverter

- CHANGELOG.md
- src/main/java/io/beanmapper/BeanMapper.java
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/config/Configuration.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/main/java/io/beanmapper/core/converter/collections/CollectionConverter.java
- src/main/java/io/beanmapper/strategy/AbstractMapStrategy.java
- src/main/java/io/beanmapper/strategy/MapCollectionStrategy.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/collections/CollTarget.java
Bug #111; when a source and target have been assigned to a collection
handler, it will now treat a null value for the source as special,
subscribing it to the BeanCollectionUsage rules (default: CLEAR).
That is, it will REUSE the target, CLEAR it, or CONSTRUCT a new one.
This is the most logical behaviour with Hibernate on the other side.
Bug #112 The validation took place before all configuration was done,
resulting in collection handlers not being available in some cases.
The validation of strict classes is done as part of the last step of
the ```BeanMapperBuilder.build()``` method, after all required steps
have been taken.
> Use null source collection and enforce build sequence

- CHANGELOG.md
- pom.xml
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/BeanPropertyMatchupDirection.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/not_accessible/source_contains_nested_class/PersonWithGetterOnlyProperty.java
- src/test/java/io/beanmapper/testmodel/not_accessible/source_contains_nested_class/SourceWithPerson.java
- src/test/java/io/beanmapper/testmodel/not_accessible/source_contains_nested_class/TargetWithPersonName.java
- src/test/java/io/beanmapper/testmodel/not_accessible/target_contains_nested_class/PersonWithSetterOnlyProperty.java
- src/test/java/io/beanmapper/testmodel/not_accessible/target_contains_nested_class/SourceWithPersonName.java
- src/test/java/io/beanmapper/testmodel/not_accessible/target_contains_nested_class/TargetWithPerson.java
On dealing with mappable nested classes in combination with a
@BeanProperty dot-delimited route, the wrong mapping direction
was applied. This resulted in errors at the moment that the field
could only be accessed through a method accessor and that the
complementing method accessor was not available (ie, get and no set,
or set and no get).
The problem has been fixed by inverting the method direction on
dealing with a mappable nested class.
> #116 Mappable nested classes analyzed for wrong direction

- CHANGELOG.md
- src/main/java/io/beanmapper/core/generics/AbstractBeanPropertyClass.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/nested_generics/SourceWithNestedGenerics.java
- src/test/java/io/beanmapper/testmodel/nested_generics/TargetWithNestedGenerics.java
When a type is a nested generic (eg, List<List<String>>) it threw a
ClassCastException, even if no mapping took place. Fixed by checking
the Type in ```AbstractBeanPropertyClass``` and calling for rawType
if it concerns a ParameterizedType.
> #118 Nested ParameterizedTypes throws a ClassCastException

- src/main/java/io/beanmapper/BeanMapper.java
- src/main/java/io/beanmapper/annotations/BeanCollection.java
- src/main/java/io/beanmapper/annotations/BeanProperty.java
- src/main/java/io/beanmapper/annotations/BeanRoleSecured.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/collections/AbstractCollectionHandler.java
- src/test/java/io/beanmapper/testmodel/othername/SourceWithOtherName.java
`@BeanProperty` could only be used with a `name` property. Adding a
`value` alias allows this annotation to be used without any prefix and
just the name of the property.
Also corrected all warnings about javadoc (missing returns).
Fixes #122
> Added value alias for @BeanProperty

- src/main/java/io/beanmapper/dynclass/ClassGenerator.java
- src/test/java/io/beanmapper/dynclass/AbstractConcurrentTest.java
- src/test/java/io/beanmapper/dynclass/ClassGeneratorTest.java
- src/test/java/io/beanmapper/dynclass/ClassStoreTest.java
- Using an ExecutorService in AbstractConcurrentTest loses too much control and certainty over what thread run which task.
- Added advice on when to use the new constructor in ClassStore
> Reverted changes in AbstractConcurrentTest

- CHANGELOG.md
- src/main/java/io/beanmapper/core/converter/impl/AnyToEnumConverter.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/enums/Day.java
- src/test/java/io/beanmapper/testmodel/enums/DayEnumSourceArraysAsList.java
- src/test/java/io/beanmapper/testmodel/enums/WeekEntity.java
- src/test/java/io/beanmapper/testmodel/enums/WeekResult.java
- src/test/java/io/beanmapper/testmodel/enums/WeekStringResult.java
- AnyToEnumConverter uses Enum#name() when mapping Enum to Enum.
- Updated tests to include an Enum with an overridden toString-method.
> Implemented fix for issue #121

- CHANGELOG.md
- src/main/java/io/beanmapper/BeanMapper.java
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/core/converter/impl/OptionalToObjectConverter.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/core/converter/impl/OptionalToObjectConverterTest.java
- src/test/java/io/beanmapper/testmodel/optional_getter/MyEntity.java
- src/test/java/io/beanmapper/testmodel/optional_getter/MyEntityResult.java
- Getters returning Optionals can be properly converted to a given target class.
- Added tests to map fields with a getter returning an optional.
- Added the changes made in the map-optional branch to this branch.
> Added support for Optional-returning getters (#137)

- CHANGELOG.md
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/main/java/io/beanmapper/core/BeanMatch.java
- src/main/java/io/beanmapper/core/BeanMatchValidationMessage.java
- src/main/java/io/beanmapper/core/BeanStrictMappingRequirementsException.java
- src/main/java/io/beanmapper/strategy/MapStrategyType.java
- src/test/java/io/beanmapper/config/CoreConfigurationTest.java
- Every method that returns a collection that may be null, will check whether the collection is null. If the collection is null, the method will return an empty, immutable collection of the correct type.
- Updated relevant tests to reflect that methods returning a collection will never return null when a collection is required.
> Methods that return a collection will always return a non-null object.

- CHANGELOG.md
- src/main/java/io/beanmapper/annotations/BeanCollection.java
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/config/Configuration.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/config/FlushAfterClearInstruction.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/main/java/io/beanmapper/config/StrictMappingProperties.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/BeanPropertyMatch.java
- src/main/java/io/beanmapper/core/collections/AbstractCollectionHandler.java
- src/main/java/io/beanmapper/core/collections/CollectionHandler.java
- src/main/java/io/beanmapper/core/converter/collections/BeanCollectionInstructions.java
- src/main/java/io/beanmapper/core/converter/collections/CollectionConverter.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/config/BeanMapperBuilderTest.java
- src/test/java/io/beanmapper/config/CoreConfigurationTest.java
- src/test/java/io/beanmapper/config/OverrideConfigurationTest.java
- src/test/java/io/beanmapper/core/converter/collections/BeanCollectionInstructionsTest.java
- Replaced the OverrideConfiguration#flushAfterClear-Boolean with enum FlushAfterClearInstruction. The FlushAfterClearInstruction-enum, just like the Boolean-wrapper, allows for three values: FlushAfterClearInstruction#FLUSH_ENABLED (true), FlushAfterClearInstruction#FLUSH_DISABLED (false) and FlushAfterClearInstruction#UNSET (null). Using this enum mitigates the unpleasant usage of the Boolean-class, and should prevent NPEs.
- Replaced the usage of Boolean with the primitive boolean, wherever possible.
- Updated tests where necessary.
> Replaced usages of Boolean-class, with primitive or enum.

- CHANGELOG.md
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/config/OverrideConfigurationTest.java
- OverrideConfiguration#withoutDefaultConverters throws a BeanConfigurationOperationNotAllowedException(String).
- OverrideConfiguration#addLogicSecuredCheck throws a BeanConfigurationOperationNotAllowedException(String).
- OverrideConfiguration#addCollectionHandler throws a BeanConfigurationOperationNotAllowedException(String)
- OverrideConfiguration#addProxySkipClass throws a BeanConfigurationOperationNotAllowedException(String).
- OverrideConfiguration#addPackagePrefix(Class<?>) throws a BeanConfigurationOperationNotAllowedException(String).
- OverrideConfiguration#addPackagePrefix(String) throws a BeanConfigurationOperationNotAllowedException(String).
- OverrideConfiguration#addAfterClearFlusher throws a BeanConfigurationOperationNotAllowedException(String).
- …
> Replaced NOPs in OverrideConfiguration with suitable Exceptions.

- CHANGELOG.md
- src/main/java/io/beanmapper/BeanMapper.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/testmodel/same_source_diff_results/Entity.java
- Added BeanMapper#map(Object[], Class) allowing users to map an array to a new array of the given type.
- Added tests.
- Expanded logging in BeanMatchStore.
- Updated CHANGELOG.md.
> Added array-mapping

- CHANGELOG.md
- src/main/java/io/beanmapper/core/constructor/DefaultBeanInitializer.java
- src/test/java/io/beanmapper/annotations/BeanConstructTest.java
- src/test/java/io/beanmapper/annotations/model/bean_construct/NestedSource.java
- src/test/java/io/beanmapper/annotations/model/bean_construct/NestedTarget.java
- src/test/java/io/beanmapper/annotations/model/bean_construct/Source.java
- src/test/java/io/beanmapper/annotations/model/bean_construct/Target.java
- src/test/java/io/beanmapper/config/BeanMapperBuilderTest.java
- src/test/java/io/beanmapper/core/constructor/DefaultBeanInitializerTest.java
- Added DefaultBeanInitializer#mapParameterizedArguments(Type[], Object[]), allowing BeanMapper to properly map constructor parameters with a type-parameter, when using the @BeanConstruct-annotation.
- Using @sptdevos' tests to confirm proper functionality.
- Updated CHANGELOG.md
> Fix for issue #130

- CHANGELOG.md
- src/main/java/io/beanmapper/dynclass/ClassGenerator.java
- src/test/java/io/beanmapper/annotations/BeanAliasTest.java
- src/test/java/io/beanmapper/annotations/model/bean_alias/DownsizeForm.java
- src/test/java/io/beanmapper/annotations/model/bean_alias/Result.java
- Modified ClassGenerator#createClass, to check whether a generated field is annotated with BeanAlias. If so, the name of the generated field will be set to the value on the BeanAlias-annotation, and the annotation will be removed from the generated field.
> Fix for issue #166

- CHANGELOG.md
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/inspector/MethodPropertyAccessor.java
- Ignoring fields with BeanIgnore-annotation when detecting field shadowing.
- Fixed problem with getting a class using the name of an accessor.
> Fixes FieldShadowingException for ignored fields.

- CHANGELOG.md
- src/main/java/io/beanmapper/BeanMapper.java
- src/main/java/io/beanmapper/config/BeanMapperBuilder.java
- src/main/java/io/beanmapper/core/constructor/DefaultBeanInitializer.java
- src/main/java/io/beanmapper/core/converter/BeanConverter.java
- src/main/java/io/beanmapper/core/converter/impl/ObjectToOptionalConverter.java
- src/main/java/io/beanmapper/core/converter/impl/OptionalToObjectConverter.java
- src/main/java/io/beanmapper/exceptions/NoSuchFieldInTargetClass.java
- src/main/java/io/beanmapper/utils/Classes.java
- src/test/java/io/beanmapper/BeanMapperTest.java
- src/test/java/io/beanmapper/core/converter/impl/OptionalToObjectConverterTest.java
- src/test/java/io/beanmapper/testmodel/optional_getter/EntityFormWithOptionalOfOptional.java
- src/test/java/io/beanmapper/testmodel/optional_getter/EntityResultWithMap.java
- src/test/java/io/beanmapper/testmodel/optional_getter/EntityWithMap.java
- src/test/java/io/beanmapper/testmodel/optional_getter/EntityWithOptional.java
- src/test/java/io/beanmapper/testmodel/optional_getter/EntityWithoutOptional.java
- src/test/java/io/beanmapper/testmodel/optional_getter/MyEntityResultWithList.java
- src/test/java/io/beanmapper/testmodel/optional_getter/MyEntityResultWithNestedOptionalField.java
- src/test/java/io/beanmapper/testmodel/optional_getter/MyEntityResultWithOptionalField.java
- src/test/java/io/beanmapper/testmodel/optional_getter/MyEntityWithList.java
- BeanMapper#map(Optional, Class) should now allows for mapping of Optional<Optional<?>> to a target class. Every Optional may also contain another Optional. The only limit is the recursion limit.
- It is now possible to automatically map Optional<X> to Optional<Y>, due to changes in the OptionalToObjectConverter.
- Supports mapping Optional<List<X>> to Optional<List<Y>>. Same for Sets.
- Added mapping Optional<Map<X>> to Optional<Map<Y>>.
> Added arbitrarily deep Optional Mapping

- CHANGELOG.md
- src/main/java/io/beanmapper/config/CollectionHandlerStore.java
- src/main/java/io/beanmapper/config/OverrideField.java
- src/main/java/io/beanmapper/config/StrictMappingProperties.java
- src/main/java/io/beanmapper/core/collections/AbstractCollectionHandler.java
- src/main/java/io/beanmapper/core/converter/collections/CollectionConverter.java
- src/main/java/io/beanmapper/core/unproxy/UnproxyResultStore.java
- src/main/java/io/beanmapper/strategy/AbstractMapStrategy.java
- src/main/java/io/beanmapper/strategy/MapToClassStrategy.java
- src/main/java/io/beanmapper/strategy/MapToDynamicClassStrategy.java
- src/main/java/io/beanmapper/utils/BeanMapperPerformanceLogger.java
- Created UnproxyResultStore, allowing for caching of unproxied classes.
- Fixed the premature evaluation of String#formatted(Object ...), by only passing String literals to the performance logger.
Closes #196 #197
> [#196/#197] implement caching for unproxy results

- CHANGELOG.md
- src/main/java/io/beanmapper/config/OverrideConfiguration.java
- src/main/java/io/beanmapper/config/OverrideField.java
- OverrideField was phased out.
- Any field that used to be an OverrideField in the OverrideConfiguration, now eagerly fetches the value from the parent. While this increases resource consumption of the OverrideConfiguration somewhat, the benefits far outweigh the cons, according to performance tests.
Closes #199
> [#199] - Phasing out OverrideField

- CHANGELOG.md
- pom.xml
- src/main/java/io/beanmapper/annotations/BeanProperty.java
- src/main/java/io/beanmapper/config/CoreConfiguration.java
- src/main/java/io/beanmapper/core/BeanMatchStore.java
- src/main/java/io/beanmapper/core/BeanPropertyWrapper.java
- src/main/java/io/beanmapper/core/inspector/BeanPropertySelector.java
- src/main/java/io/beanmapper/dynclass/ClassGenerator.java
- src/main/java/io/beanmapper/exceptions/DuplicateBeanPropertyTargetException.java
- src/main/java/io/beanmapper/exceptions/FieldShadowingException.java
- src/test/java/io/beanmapper/annotations/BeanPropertyTest.java
- src/test/java/io/beanmapper/annotations/model/bean_property/ComplexInvalidPersonForm.java
- src/test/java/io/beanmapper/annotations/model/bean_property/ComplexPerson.java
- src/test/java/io/beanmapper/annotations/model/bean_property/ComplexPersonResult.java
- src/test/java/io/beanmapper/annotations/model/bean_property/InvalidPersonForm.java
- src/test/java/io/beanmapper/annotations/model/bean_property/Person.java
- src/test/java/io/beanmapper/annotations/model/bean_property/PersonForm.java
- src/test/java/io/beanmapper/annotations/model/bean_property/PersonResult.java
- src/test/java/io/beanmapper/annotations/model/bean_property/ShadowedPersonResult.java
- src/test/java/io/beanmapper/config/BeanMapperBuilderTest.java
- src/test/java/io/beanmapper/core/collections/SetCollectionHandlerTest.java
- src/test/java/io/beanmapper/core/inspector/BeanPropertySelectorTest.java
- src/test/java/io/beanmapper/core/inspector/models/bean_property_selector/BeanPropertyImpl.java
- src/test/java/io/beanmapper/strategy/ConstructorArgumentsTest.java
- Made BeanProperty repeatable.
- Added BeanProperty#targets, allowing users to specify which mappings the specified BeanProperty should apply to.
- Compatibility with existing usages of the BeanProperty-annotation.
Closes: #188
> Fix #188: Make BeanProperty repeatable
